services:
  db:
    image: mongo:latest
    container_name: GoInn
    env_file:
      - app.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

volumes:
  db-data:
